Trying a fix
 docker-compose up mosquitto
Building mosquitto
Step 1/7 : FROM alpine:edge
 ---> f96c4363411f
Step 2/7 : MAINTAINER David Audet <david.audet@ca.com>
 ---> Using cache
 ---> 8a17f4849620
Step 3/7 : LABEL Description "Eclipse Mosquitto MQTT Broker"
 ---> Using cache
 ---> 5dad4d08fdb0
Step 4/7 : RUN apk --no-cache add mosquitto=1.4.14-r1 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     cp /etc/mosquitto/mosquitto.conf /mosquitto/config &&     chown -R mosquitto:mosquitto /mosquitto
 ---> Running in 0c7bd554572f
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mosquitto-1.4.14-r2:
    breaks: world[mosquitto=1.4.14-r1]
Service 'mosquitto' failed to build: The command '/bin/sh -c apk --no-cache add mosquitto=1.4.14-r1 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     cp /etc/mosquitto/mosquitto.conf /mosquitto/config &&     chown -R mosquitto:mosquitto /mosquitto' returned a non-zero code: 1